### ISSUE TITLE
启动之后，访问时报错，最新的几个版本都试过了，都是报同样的错，

### ISSUE THREAD

**Issue by perfectSymphony** [XPoet/hexo-theme-keep#52]
ERROR {
  err: TypeError: /Users/macos/Desktop/v/blog/themes/keep/layout/layout.ejs:3
      1| <!DOCTYPE html>
      2| <html lang="<%= config.language %>">
   >> 3| <%- partial('_partial/head') %>
      4| <body>
      5| <%- body %>
      6| <%- partial('_partial/scripts') %>
  
  /Users/macos/Desktop/v/blog/themes/keep/layout/_partial/head.ejs:32
      30|     <%- favicon_tag(theme.style.favicon) %>
      31|     <%- css('css/style') %>
   >> 32|     <%- __css('css/font-awesome.min.css') %>
      33|     <%- export_config() %>
      34| </head>
      35| 
  
  this.url_for is not a function
      at /Users/macos/Desktop/v/blog/node_modules/hexo/lib/plugins/helper/css.js:27:54
      at Array.forEach (<anonymous>)
      at Hexo.cssHelper (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/plugins/helper/css.js:20:17)
      at Object.<anonymous> (/Users/macos/Desktop/vue/blog/themes/keep/scripts/helpers/helper.js:73:12)
      at eval (/Users/macos/Desktop/vue/blog/themes/keep/layout/_partial/head.ejs:57:17)
      at head (/Users/macos/Desktop/vue/blog/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/Users/macos/Desktop/vue/blog/themes/keep/layout/layout.ejs:13:17)
      at layout (/Users/macos/Desktop/vue/blog/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:39:17)
      at /Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/macos/Desktop/v/blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:102:5) {
    path: '/Users/macos/Desktop/vue/blog/themes/keep/layout/layout.ejs'
  }
} Render HTML failed: index.html
Unhandled rejection TypeError: /Users/macos/Desktop/v/blog/themes/keep/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%= config.language %>">
 >> 3| <%- partial('_partial/head') %>
    4| <body>
    5| <%- body %>
    6| <%- partial('_partial/scripts') %>

/Users/macos/Desktop/v/blog/themes/keep/layout/_partial/head.ejs:32
    30|     <%- favicon_tag(theme.style.favicon) %>
    31|     <%- css('css/style') %>
 >> 32|     <%- __css('css/font-awesome.min.css') %>
    33|     <%- export_config() %>
    34| </head>
    35| 

this.url_for is not a function
    at /Users/macos/Desktop/v/blog/node_modules/hexo/lib/plugins/helper/css.js:27:54
    at Array.forEach (<anonymous>)
    at Hexo.cssHelper (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/plugins/helper/css.js:20:17)
    at Object.<anonymous> (/Users/macos/Desktop/vue/blog/themes/keep/scripts/helpers/helper.js:73:12)
    at eval (/Users/macos/Desktop/vue/blog/themes/keep/layout/_partial/head.ejs:57:17)
    at head (/Users/macos/Desktop/vue/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/Users/macos/Desktop/vue/blog/themes/keep/layout/layout.ejs:13:17)
    at layout (/Users/macos/Desktop/vue/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/macos/Desktop/vue/blog/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler 
(/Users/macos/Desktop/v/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/macos/Desktop/vue/blog/node_modules/bluebird/js/release/async.js:102:5)

**Comment by XPoet** [comment]
请提供
1. 操作系统
2. Node.js 版本
3. Hexo 版本
4. Hexo 项目下的 package.json 文件

**Comment by perfectSymphony** [comment]
1、mac
2、14.7.0
3、5.0.0
4、

> `{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
}`

**Comment by XPoet** [comment]
执行命令 `hexo -v` 
把打印出来的信息发我看下

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/105622441-c45eba80-5e4c-11eb-8bab-b1a881fdd4b8.png)

**Comment by perfectSymphony** [comment]
![image](https://user-images.githubusercontent.com/26551499/105622556-70a0a100-5e4d-11eb-9d37-3f8833ae0879.png)

**Comment by perfectSymphony** [comment]
`macos@bogon blog % hexo -v
INFO  Validating config
hexo: 5.0.0
hexo-cli: 4.1.0
os: Darwin 20.2.0 darwin x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0`

**Comment by XPoet** [comment]
我模拟了你的环境，能正常运行。

**Comment by XPoet** [comment]
你新建一个 Hexo 项目，再使用 keep 主题试试看。

**Comment by perfectSymphony** [comment]
可能是我工程里面太杂了，重新建一个就可以了
