### ISSUE TITLE
hexo-all-minifier 报错

### ISSUE THREAD

**Issue by TildenJ** [XPoet/hexo-theme-keep#92]
`hexo-all-minifier` 与`lazyload` 同时开启会产生一个 Bug。

## 复现方法

主题配置同时打开 `hexo-all-minifier` 与`lazyload` ：

```yml
all_minifier: true
```

和

```yml
lazyload:
  enable: true
```

文章里输入自闭合的 `img` 标签，如：

```markdown
<img src="img.png" />

typora 中使用图片缩放功能会自动生成如下标签：
<img src="img.png" style="zoom:50%;" />
```

此时 `hexo g`  或者 `hexo s` 会报错：

```
at new HTMLParser (C:\test\tmp\node_modules\html-minifier-terser\src\htmlparser.js:244:13)
      at minify (C:\test\tmp\node_modules\html-minifier-terser\src\htmlminifier.js:993:3)
      at exports.minify (C:\test\tmp\node_modules\html-minifier-terser\src\htmlminifier.js:1354:16)
      at Hexo.OptimizeHTML (C:\test\tmp\node_modules\hexo-all-minifier\lib\optimizeHTML.js:24:14)
... ...
(C:\test\tmp\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Render HTML failed: 2021/04/27/hello-world/index.html
Unhandled rejection Error: Parse Error: <img
                     lazyload
                     src="/images/loading.svg"
                     data-src="https://cdn.jsdelivr.net/***5.png"
                      /
                >
```
原因应该是 `lazyload-handle.js `  解析返回的自闭合 `img` 标签无法被 `html-minifier-terser` 识别。

## 解决方法

经过简单测试，把 `lazyload-handle.js `文件：

https://github.com/XPoet/hexo-theme-keep/blob/8df31656038e0c9f330cc20cd3c63bb6cf66c5f5/scripts/filters/lazyload-handle.js#L9

```javascript
/<img([^>]*)src="([^"]*)"([^>]*)>/gim, 
```
改为：
```javascript
/<img([^>]*)src="([^"]*)"([^>\/]*)\/?\s*>/gim,
```
就能修复，相当于把自闭合的 `<img .../    >` 转换成了不闭合的 `<img ...>` 返回。

**Comment by XPoet** [comment]
@TildenJ 
👍 小伙伴真是太贴心了，感谢发现并指出问题。帮忙提个 PR 修复该 Bug 吧，我合并
